### ISSUE TITLE
Current r2m2 roadmap

### ISSUE THREAD

**Issue by guedou** [guedou/r2m2#4]
From highest to lowest priority:
- [x] Travis: add OS X support
- [x] build and publish a docker image on https://hub.docker.com
- [x] create an asciinema video
- [x] improve the README
- [x] update the docker hub description
- [x] create a demo VM on https://dply.co/
- [x] add examples/
- [x] add a Python only r2 ad plugin into examples/
- [x] remove docker pull in Dply script
- [x] add a link to https://guedou.github.io + fix miasm link
- [x] add support for calling conventions
- [x] cache the miasm Machine object
- [ ] miasm_asm(): asm then dis to compare the result
- [ ] move Python code into a dedicated Python module
- [ ] add a requirements.txt file and use pip
- [ ] install using r2pm
- [ ] better miasm2 expressions type checking in Ae
- [ ] detect dependencies with make
- [ ] log into r2m2.log & use the R2M2_LOG env variable
- [ ] support user-defined Python module
- [ ] use brew on OS X
- [ ] push the docker image from Travis
